Average distance and variogram at lag=0
JuliaEarth/Variography.jl pull request #28
Opened 2020-09-12 13:04 UTC by rmcaixeta

Hi @juliohm 
Check out if you're comfortable with this solution
For lag==0, I tested two scenarios: with an assertion error and with a warning (the second one is in this pull request). None of them decreased the speed performance. I chose the warning solution because it's less radical, just ignoring the duplicate pairs and doesn't crash.
For average distance, I used the previous fixed lags if counts == 0, in case it affects plots or something else

2020-09-12 13:50 UTC, juliohm requested changes
Very nice @rmcaixeta , thanks for fixing the issue. Can you please address some minor details before we merge? It would be also nice if you could share the benchmark results you got w/o the warning message.

2020-09-12 13:50 UTC, juliohm commented on src/empirical.jl
> +    sums, cumdists, counts = ball_search_accum(sdata, var₁, var₂, hmax, nlags, distance)
Could you please rename these variables to `xsums` and `ysums`. This way we can repeat the code for abscissa and ordinate:

```julia
abscissa = @. xsums / counts
ordinate = @. (ysums / counts) / 2
```

2020-09-12 13:50 UTC, juliohm commented on src/empirical.jl
> +  abscissa[counts .== 0] .= range(δh/2, stop=hmax - δh/2, length=nlags)[counts .== 0]
I wonder if we can simplify this adjustment. Perhaps create the range object right after the `δh`:

```julia
lags = range(...)
```

and then index it here with:

```julia
abscissa[counts .== 0] .= lags[counts .== 0]
```

2020-09-12 13:50 UTC, juliohm commented on src/empirical.jl
> +  cumdists = zeros(nlags)
xsums and ysums would be nicer names :+1:

2020-09-12 13:50 UTC, juliohm commented on src/empirical.jl
> +      if lag ≤ nlags && !ismissing(v) && lag != 0
what about `0 < lag <= nlags && !ismissing(v)`?

2020-09-12 13:50 UTC, juliohm commented on src/empirical.jl
>        end
Maybe move this warning to right after the `lag` calculation:

```julia
lag == 0 && @warn "duplicate coordinates found"
```

2020-09-12 16:24 UTC, juliohm requested changes
Awesome. Thanks for the quick fixes. There is one more place that we need to change for this generalization, which is the `merge` operation. Now that we have varying lags, we need to do the same thing we do for the y coordinate, a weighted average. Could you please adapt the `merge` function?

After that, it would be important to add a few tests for this use case with varying lags. Also, some tests for the `merge` function if it doesn't have already.

Thanks again for this nice improvement.

2020-09-12 16:24 UTC, juliohm commented on src/empirical.jl
> +  ysums   = zeros(nlags)
please remove the extra whitespace in this line :+1:

2020-09-12 16:24 UTC, rmcaixeta commented
Thanks for the hints
All done now. Here the benchmarks:

- PR version:
```shell
julia -t 4
(@v1.5) pkg> dev "/home/rafa/git/GeoStats/Variography.jl"
julia> using BenchmarkTools, Random, GeoStatsImages, GeoStats
julia> Random.seed!(2020);
julia> 𝒦 = geostatsimage("Ketton")
julia> 𝒮 = sample(𝒦, 1_000_000, replace=false)
julia> 𝒫 = partition(𝒮, PlanePartitioner((0.,0.,1.)))
julia> @btime EmpiricalVariogram(𝒫, :grain)
  35.213 s (1348995822 allocations: 24.50 GiB)
EmpiricalVariogram
  abscissa: (1.197456644428756, 35.21185783751248)
  ordinate: (0.01884900063055705, 0.11268282931405581)
  N° pairs: 107469329
```

- Original version:
```shell
julia -t 4
(@v1.5) pkg> free Variography
julia> using BenchmarkTools, Random, GeoStatsImages, GeoStats
julia> Random.seed!(2020);
julia> 𝒦 = geostatsimage("Ketton")
julia> 𝒮 = sample(𝒦, 1_000_000, replace=false)
julia> 𝒫 = partition(𝒮, PlanePartitioner((0.,0.,1.)))
julia> @btime EmpiricalVariogram(𝒫, :grain)
  35.516 s (1348994028 allocations: 24.50 GiB)
EmpiricalVariogram
  abscissa: (0.9015611460128481, 35.16088469450108)
  ordinate: (0.01884900063055705, 0.11268282931405581)
  N° pairs: 107469329
```

2020-09-12 16:26 UTC, juliohm commented
That is really nice. Appreciate if you can take a look at the latest review round. We still need to fix `merge` and add some tests with varying lags.

2020-09-12 16:28 UTC, rmcaixeta commented
Simultaneous comments, didn't see yours earlier. Ok, I guess I can check the `merge` later tomorrow

2020-09-12 16:28 UTC, juliohm commented
Fix https://github.com/JuliaEarth/GeoStats.jl/issues/119
Fix https://github.com/JuliaEarth/GeoStats.jl/issues/118

2020-09-12 16:29 UTC, juliohm commented
Thanks for putting the time into it. The merge should be quick to fix when you find time. It is basically repeating the same operation we do for `y` now for `x` too.

2020-09-13 11:49 UTC, rmcaixeta commented
Done with adjustments for merge function. For the tests, you meant to update the test/empirical.jl travis tests considering these changes? Anyway, I will postpone them, have some other projects here for the next free days

2020-09-13 12:47 UTC, juliohm commented
Amazing PR @rmcaixeta , thanks again for improving it. Yes, it would be nice to have a small test reproducing the behavior you wanted in your use case. Also, you can see that some of the old tests are now failing (see Travis CI results above) because the new lags are more flexible. It would be nice to fix these too.

2020-09-13 15:00 UTC, juliohm commented on src/empirical.jl
>  assuming that both variograms have the same abscissa.
We can eliminate this line from the docstring as well :+1:

2020-09-18 23:16 UTC, rmcaixeta commented
Quick adjust, that's what I can contribute this weekend. Tests passing now (I guess, waiting for Travis), and adjusted the docstring

2020-09-19 10:14 UTC, juliohm commented
That is awesome @rmcaixeta , thanks for this nice improvement. Merging it right away, feel free to add more tests in a future PR to cover the use case you had in mind, which motivated the generalization.

2020-09-19 10:14 UTC, merged